name: Python tests

on: [push, workflow_dispatch]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        # https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python
        with:
          python-version: "3.x"
          cache: "pip"
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          python3 -m pip install -e .
      - name: Create empty config.txt
        # Otherwise when importing config.py, before any mock is created, it fails cause config.txt does not exist
        run: |
          cp config.txt.default config.txt
      - name: Test with pytest
        run: |
          python3 -m pytest
      - name: Test the CLI
        run: |
          if STDERR=$(python3 -m home_automation 2>&1 1>/dev/null); then
            echo "Should have failed"
            false
          fi
          [ "STDERR" = "No action given." ] || false

          if STDERR=$(python3 -m home_automation yolo 2>&1 1>/dev/null); then
            echo "Should have failed"
            false
          fi
          [ "STDERR" = "Unkown action: yolo" ] || false
